-- 1) Criar a tabela
create table codigos_acesso (
  id bigint generated always as identity primary key,
  codigo text unique not null,
  usado boolean not null default false,
  usado_em timestamptz,
  usado_ip text
);

-- 2) Habilitar RLS (Row Level Security)
alter table codigos_acesso enable row level security;

-- 3) Permitir leitura pública (para checar se o código existe)
create policy "leitura publica" on codigos_acesso
  for select using (true);

-- 4) Permitir update público SOMENTE para marcar como usado
--    (impede alterar codigo, e impede "desmarcar" um usado=true)
create policy "marcar como usado" on codigos_acesso
  for update using (usado = false)
  with check (usado = true);

-- 5) Inserir os 100 códigos
insert into codigos_acesso (codigo) values
  ('AF-28AY-V24Q'),
  ('AF-2MV3-AVUP'),
  ('AF-2TQW-DQCW'),
  ('AF-2XB9-WM9P'),
  ('AF-3L7J-B3BF'),
  ('AF-3TEP-WP93'),
  ('AF-3XGR-NN6J'),
  ('AF-3Z66-HRQE'),
  ('AF-49U3-C7FW'),
  ('AF-4Q6T-AL5X'),
  ('AF-5CBF-PQBN'),
  ('AF-5H2N-SC5A'),
  ('AF-5J7M-DS2W'),
  ('AF-5MT7-RE6G'),
  ('AF-5QM7-DRH7'),
  ('AF-5TCA-XJSL'),
  ('AF-5W76-6P8L'),
  ('AF-5Y54-7DGD'),
  ('AF-65AH-EKCZ'),
  ('AF-6SRT-9RT6'),
  ('AF-7GEP-SJYE'),
  ('AF-7K5M-T875'),
  ('AF-7KSJ-RS53'),
  ('AF-7U59-KNUP'),
  ('AF-8TUG-NUQZ'),
  ('AF-8Y4X-WGLX'),
  ('AF-9EDK-KVFR'),
  ('AF-9QT5-9B2X'),
  ('AF-9UT4-88R7'),
  ('AF-A4FQ-H7HK'),
  ('AF-ASMG-VNKZ'),
  ('AF-BRNB-KRJ8'),
  ('AF-CF4W-SPWR'),
  ('AF-DAFR-L498'),
  ('AF-DDWD-D8LD'),
  ('AF-ECXE-RT9P'),
  ('AF-EDLV-U6H7'),
  ('AF-EURT-XWFJ'),
  ('AF-EXA4-9G5Z'),
  ('AF-F8BD-YQEC'),
  ('AF-FMEE-R3HR'),
  ('AF-FUQ3-RVZ8'),
  ('AF-FUXF-RVQN'),
  ('AF-GJSH-GKTU'),
  ('AF-H4Q2-66V5'),
  ('AF-HBTR-QJGF'),
  ('AF-HP7S-ZLHL'),
  ('AF-HTXH-U5L7'),
  ('AF-J7W6-56L8'),
  ('AF-J8LS-5PNV'),
  ('AF-J8R8-4NGG'),
  ('AF-J9GA-U886'),
  ('AF-K2NJ-ET4X'),
  ('AF-K5JC-VZCY'),
  ('AF-KBCR-8E74'),
  ('AF-KQ2K-PE44'),
  ('AF-L5E2-27SA'),
  ('AF-LAW9-BHZV'),
  ('AF-LG2C-8QN7'),
  ('AF-M4BM-X4RT'),
  ('AF-M86T-M59F'),
  ('AF-MVAJ-TCDU'),
  ('AF-N293-RKAG'),
  ('AF-NZ5E-XWHV'),
  ('AF-NZ96-DPTJ'),
  ('AF-P3DL-2A2S'),
  ('AF-P7WX-2T4S'),
  ('AF-PRGY-4KRL'),
  ('AF-PXPS-9SDF'),
  ('AF-QG2T-7ZLZ'),
  ('AF-QHNW-HMNP'),
  ('AF-R49R-896B'),
  ('AF-RDRF-F9EJ'),
  ('AF-RGVH-CY5Z'),
  ('AF-RMEL-A468'),
  ('AF-RZUL-6VAV'),
  ('AF-S3JV-7WEA'),
  ('AF-SMSC-G5YW'),
  ('AF-SN5H-QKTK'),
  ('AF-SWH3-A74D'),
  ('AF-TETY-3XBH'),
  ('AF-TKPX-GF2G'),
  ('AF-TWRF-T6R7'),
  ('AF-U69H-BRLV'),
  ('AF-UCQU-U7EQ'),
  ('AF-UZNE-CQUF'),
  ('AF-V3T9-6FC5'),
  ('AF-V4W3-UJN4'),
  ('AF-VDGP-PSFL'),
  ('AF-VGBV-23NE'),
  ('AF-WSBF-QBTC'),
  ('AF-X74D-P42B'),
  ('AF-XBQQ-AEDQ'),
  ('AF-XMDS-8HE3'),
  ('AF-Y5XY-7TVS'),
  ('AF-YPTE-LRL7'),
  ('AF-YSXT-TANF'),
  ('AF-YVQQ-BN3X'),
  ('AF-YYSC-7H2F'),
  ('AF-ZQJ9-FDHK');
